name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install theme
        run: git clone https://github.com/jieiku/abridge.git themes/abridge
      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola
      - name: zola build
        run: zola build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
